name: buscarviagens
description: "Aplicativo de busca de passagens aéreas."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Ícones do iOS
  cupertino_icons: ^1.0.8

  # Gerenciamento de estado e navegação
  get: ^4.7.2

  # Para fazer requisições HTTP
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints para boas práticas de código
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Registro dos arquivos JSON dentro de assets/
  assets:
    - assets/aeroportos.json
